// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddUserToProject(ctx context.Context, arg AddUserToProjectParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteProject(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectRole(ctx context.Context, id int64) (ProjectRole, error)
	GetProjectRoleByName(ctx context.Context, name string) (ProjectRole, error)
	GetProjectUsers(ctx context.Context, projectID int64) ([]GetProjectUsersRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserProjects(ctx context.Context, userID int64) ([]GetUserProjectsRow, error)
	ListProjectRoles(ctx context.Context) ([]ProjectRole, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveUserFromProject(ctx context.Context, arg RemoveUserFromProjectParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserProjectRole(ctx context.Context, arg UpdateUserProjectRoleParams) error
}

var _ Querier = (*Queries)(nil)
